### ISSUE TITLE
etcd nodes failing health check

### ISSUE THREAD

**Issue by od0** [kz8s/tack#111] opened 2016-11-13 17:38 UTC
![image](https://cloud.githubusercontent.com/assets/2206712/20247586/b73f11c8-a984-11e6-91f1-dfe573004f59.png)

This prevents the setup from completing (hangs on `Curling apiserver external elb`)

**Comment by yagonobre** [comment] 2016-11-13 17:42
The instances need some time to get in service

**Comment by od0** [comment] 2016-11-13 17:56
@yagonobre thanks - gave it a long time (30+ minutes). The instances are live and can be ssh'd into. Looks like the kubelet may be failing to start

This may be a terraform issue. I had upgraded to the latest (0.7.10) before creating a new cluster. When I rolled back to 0.7.7, everything ran successfully.

**Comment by lachie83** [comment] 2016-11-14 06:58
I was having the same issue. My guess is that 0.7.10 is truncating the cloud-config. Seeing this on the etcd instances

```
-- Logs begin at Mon 2016-11-14 06:40:09 UTC. --
Nov 14 06:41:15 ip-172-25-128-10.us-west-2.compute.internal systemd[936]: Reached target Default.
Nov 14 06:41:15 ip-172-25-128-10.us-west-2.compute.internal systemd[936]: Startup finished in 11ms.
Nov 14 06:41:15 ip-172-25-128-10.us-west-2.compute.internal systemd[1]: Started User Manager for UID 500.
Nov 14 06:41:19 ip-172-25-128-10.us-west-2.compute.internal locksmithd[768]: [etcd.service etcd2.service] are inactive
Nov 14 06:41:19 ip-172-25-128-10.us-west-2.compute.internal locksmithd[768]: Unlocking old locks failed: [etcd.service etcd2.service] are inactive. Retrying in 40s.
```

**Comment by lachie83** [comment] 2016-11-14 07:00
Confirmed the issue is resolved when reverting to terraform 0.7.7

**Comment by tylux** [comment] 2016-11-18 21:55
Is this fixed in Terraform 0.7.11?

**Comment by od0** [comment] 2016-11-19 00:04
@tylux haven't tried yet - afraid to touch anything ;)

**Comment by od0** [comment] 2016-11-19 00:24
@tylux tried a fresh install, same issue

**Comment by blockloop** [comment] 2016-11-30 05:53
Still having the issue on TF 0.7.13

**Closed as completed** 2016-12-21 17:56 UTC
